### ISSUE TITLE
move the specified event handler into redis

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#102]
When there is more than one worker, it is a burden on the administrator to get the same event handler on all the machines.  If the event handler is stored in redis when the 'start' command is issued, all workers can get/load the event handler when it's time to work.

**Comment by trel** [comment]
We implemented Option 2.  Testing showed that Python optimized enough that 2 was similar to 3.

**Comment by gabiiiiiii** [comment]
Performance testing was executed through a test harness in docker. The containers needed for the test consisted of:

- Ingest-worker
- Irods-catalog-provider
- redis
- Postgres:10.12.

- Testing with Traffic Control:
Each branch was run with 1000 files and increased traffic control from 1 to 25ms to compare the run time. Master ran linearly while event_handler and event_handler_cached ran nearly linearly. 

- Testing without Traffic Control:
Each version was run with an incremental amount of files starting at 100 going to 1,000,000 to compare the runtime. Master ran linearly, event_handler_cached ran nearly linearly, and event_handler seemed to run exponentially. 

In all cases of testing master was the fastest, followed by event_handler_cached, and then event_handler. The trade off for performance was decided in order to create more convenience for the user.

**Comment by trel** [comment]
Thanks @gabiiiiiii !
