### ISSUE TITLE
sync_task.py fails to run on python 3

### ISSUE THREAD

**Issue by Rob1king** [irods/irods_capability_automated_ingest#119]
Method defined at line 107 uses async as the name, this is a reserved word in python 3.

The method is called at lines 301, 343, 360, 366 and 518.

**Comment by alanking** [comment]
While this is in fact a reserved keyword, automated ingest *only* works in python 3. In fact, it is required to use python 3.5 or greater in order to function properly. I am using the python:3.5 tagged Docker image to test ingest and it works fine for me.

Is there a newer version of python 3 that changed the rules? What version of python are you testing against?

As a side note, I am in the process of completely re-writing this tool  and the async method has been removed, so this will go away in the next release.

**Comment by Rob1king** [comment]
I'm using 3.7.5. The error occurs when I attempt to start the celery worker.

File "/xxx/xxxxx/xxxx/irods/lib/python3.7/site-packages/irods_capability_automated_ingest/sync_task.py", line 107
    def async(r, logger, task, meta, queue):
            ^
SyntaxError: invalid syntax

**Comment by trel** [comment]
async is reserved in 3.7+

https://docs.python.org/3/whatsnew/3.7.html

**Comment by trel** [comment]
duplicate of #149
