### ISSUE TITLE
check for valid source directory and collection name, zone name

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#31]
Currently,   if we give incorrect zone name or collection name by mistake, it runs for ever and it does not check and throws an error saying invalid source directory path, or invalid zone name,  or invalid collection name/path.

**Comment by masilamani** [comment]
For example: Try with giving invalid zone as target collection

python -m irods_capability_automated_ingest.irods_sync start /tmp/ingest /INVALIDZone/home/rods/tmp/ingest

**Comment by alanking** [comment]
I was able to reproduce the issue with an invalid zone name. The job will hang and needs to be stopped manually.

I'm not sure how you would give an invalid collection name (perhaps if you didn't have permission to write in the target collection?), but after trying a few things I was not able to reproduce for that scenario. Using an invalid source directory results in the job failing out and stopping with `FileNotFoundError`. This issue is fairly old, so these cases may have been resolved somewhere along the way.
