### ISSUE TITLE
Allocate N number of worker process to the given Ingest job 

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#32]
In order to support multiple ingest job at the same time,  need to allocate ONLY N (e.g. 8 or 16) number of worker process out of available number of worker process (e.g. 40 or 32) to the given Ingest job.

Currently, when we run the long running ingest job of the large volume of files ( e.g. 1 million +), then it consumes all worker process for this one ingest job and any other sub-sequent smaller ingest job will be blocked and has to wait till first ingest completes.

**Comment by alanking** [comment]
The task queues operate off of keys in Redis. There can only be one queue of a certain name per Redis instance due to the nature of keys. In this case, if you start up 40 workers and point them at the same Redis database, there will only be one queue to work with.

For your use case, could you just start up 8 or 16 workers in one window with the `CELERY_BROKER_URL` pointing to instance 0, then start up 8 or 16 workers in another window with the `CELERY_BROKER_URL` pointing to instance 1, etc. for as many as you need/can handle? In this way, each Redis instance is managing a different job and therefore a different set of queues. Of course, wherever you start the irods_syncs will need to be pointing to the correct Redis instances as well.

Just a thought. I have not tried this myself to see if it works.

**Comment by alanking** [comment]
Previous comment outlines a couple of strategies for achieving this. No changes needed in the tool. Closing.
